#FROM jenkins/jenkins:2.60.3-alpine
#From jenkins/jenkins:2.452.1-jdk17
#User root
#FROM jenkins/jenkinslatest-jdk17
#RUN apk update && apk install -y openjdk-17*
#USER root
#RUN apt-get update && apt-get install -y lsb-release
#COPY ca.pem /usr/local/share/ca-certificates/
#RUN update-ca-certificates



