services:
  jenkins:
    build: jenkins/jenkins:2.60.3-alpine
    container_name: jenkins_box_lts1
    user: root
    ports:
      - "8081:8081"
      - "50001:50001"
    volumes:
      - /local/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- /local/certs:/usr/local/share/ca-certificates
      #local storage path : docker jenkins storage path
