services:
  jenkins:
    build: .
    container_name: jenkins_box_lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /local/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /local/certs:/usr/local/share/ca-certificates
      #local storage path : docker jenkins storage path
    #restart: restart
